### ISSUE TITLE
npm ERR! 404 Not Found: TEMPLATE@latest

### ISSUE THREAD

**Issue by StefanWerW** [shadowmint/unity-package-template#1]
Error on npm install.

log:
> npm install TEMPLATE --save
    npm ERR! code E404
    npm ERR! 404 Not Found: TEMPLATE@latest

**Comment by shadowmint** [comment]
This is a template file.

For a real example try `npm install --save shadowmint/unity-n-core`

The template you are expected to fork and customize, not install.

**Comment by StefanWerW** [comment]
Apparently your package is not in npm registry. Have you published it? https://www.npmjs.com/package/TEMPLATE   ----> 404

**Comment by StefanWerW** [comment]
Got it. Thanks.

**Comment by shadowmint** [comment]
(there is nothing special about the install url; npm install foo/bar
installs github.com/foo/bar as a package)

On Dec 14, 2017 6:21 PM, "Doug" <douglas.linder@gmail.com> wrote:

This is a template file.

For a real example try `npm install --save shadowmint/unity-n-core`

The template you are expected to fork and customize, not install.
